[package]
name = "desktop_ai"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.24.9"
ndarray = "0.15.1"
onnxruntime = "0.0.14"
screenshots = "0.8.10"
serde = "1.0.227"
serde_derive = "1.0.227"
serde_json = "1.0.145"
